apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - pvc-fotos.yaml
  - route.yaml
  - secret.yaml
  - configmap.yaml
