apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dccheck-fotos-pvc
  labels:
    app: dccheck-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
